spring:
  datasource:
    url: jdbc:mysql://localhost:3306/festival_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 자동으로 테이블 생성/업데이트
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080