name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend/Phoenixia


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Upload to EC2 and run
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 43.200.163.118
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: Backend/Phoenixia/build/libs/*.jar
          target: /home/ubuntu/

      - name: Run remote deploy commands
        uses: appleboy/ssh-action@v1.0.3
        continue-on-error: true
        with:
          host: 43.200.163.118
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            pkill -f 'Phoenixia-0.0.1-SNAPSHOT.jar' || true
            nohup java -jar /home/ubuntu/Phoenixia-0.0.1-SNAPSHOT.jar > /home/ubuntu/app.log 2>&1 &
            sleep 3  # 컨테이너가 너무 빨리 종료되는 것 방지

      - name: Log Booth.java
        run: cat src/main/java/com/cloud/phoenixia/domain/booth/Booth.java